module:
  ban: 0
  block: 0
  block_content: 0
  breakpoint: 0
  content_moderation: 0
  dblog: 0
  dynamic_page_cache: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  img: 0
  language: 0
  locale: 0
  md: 0
  media: 0
  media_library: 0
  node: 0
  page_cache: 0
  path: 0
  path_alias: 0
  search: 0
  simple_sitemap: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  workflows: 0
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stark: 0
  seven: 0
  pu10g: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: ja
